### ISSUE TITLE
Putting the Linker into Action

### ISSUE THREAD

**Issue by flexoron** [davidlattimore/wild#12]
```
I rejoice over this advanced project and like to ask advice from you.

Subject: Improving cold build compilation time of a Prolog implementation.

debug = 0
incremental = true
Finishes the [optimized] target in 2m 30s
Prolog application performance test:
 % CPU time: 8.7s

Putting the Linker into action:

rustflags = ["-C", "linker-plugin-lto"]
Finishes the [optimized] target in 2m 00s
Also, the performance of the application is better
 % CPU time: 7.5s

Warm build finishes in 50s

Do you think incremental linking can solve this issue?
Or perhaps 'wild' amplified up with linkage editor technics
could be another cool option for lto-mixin speedup linking.

I would like to stay with linker-plugin-lto.

Thank you very much.
```
https://github.com/mthom/scryer-prolog/issues/2359

**Comment by davidlattimore** [comment]
It should in theory be possible to some form of LTO even when doing incremental linking. See #1. How much this will take to implement, I'm unsure of.

Generally I'd only use LTO, especially fat LTO for release builds, not for day-to-day development. Release builds generally shouldn't be incrementally linked. So to an extent, although LTO and incremental linking could go together, they're probably not ideal together.

I only briefly looked at the issue you linked to, but if your goal is to speed up cold builds, then one option might be to not use thin LTO instead of fat LTO. Assuming that results in your application getting reduced performance, you could then profile it to try to understand the differences between the fat and thin LTO versions. It's possible that there might be just a handful of hot functions in different compilation units that are getting inlined more in the fat LTO version. In that case, marking those functions as `#[inline]` might help you to get back some of the speed lost by switching to thin LTO.

**Comment by flexoron** [comment]
Yes, ok..
I look at all this from a Prolog point of view and, for example,
for the test-program mentioned this is useless:
Finished `dev` profile [unoptimized + debuginfo] target(s) in `25.94s` % very good
 % CPU time: `436.145s` % well, very bad.
The best solution for this one is debug=0, incremental=true and linker-plugin-lto.
Anyway! Thank you for the hints.

Btw
Does this work already?  I don't have musl.
[target.x86_64-unknown-linux-gnu]
rustflags = [ "-C", "relocation-model=static", "-C", "link-arg=--ld-path=wild" ]

**Comment by davidlattimore** [comment]
The linker does now work with glibc (not just musl) and even works with dynamic linking to an extent. However there are still bugs and / or things that it doesn't support that need to be fixed. I wouldn't suggest actually using wild as your linker for day-to-date use at this stage.

For some projects, I set `opt_level=1` or `opt_level=2` for dev builds. This might provide a fast enough binary to be usable for development without being too slow to build.

**Comment by flexoron** [comment]
Great! It works. Thanks a lot.
