### ISSUE TITLE
Use of `object` crate

### ISSUE THREAD

**Issue by philipc** [davidlattimore/wild#4]
I was having a look at the code because I'm interested in seeing how people make use of the `object` crate.

You are making extensive use of the unified API for reading ELF files. Is this intentionally so that you can handle other file formats in future, or just because it was easiest? A concern I have with this approach is that, to support the unified API, the relocation parsing in `object` is doing a bunch of work that you don't need, and this may be an area that is performance sensitive.

Also, you have defined your own ELF types for use in writing (e.g. `FileHeader`, `ProgramHeader`). Is there a reason that the types defined in `object::elf` weren't suitable?

**Comment by davidlattimore** [comment]
Thanks for having a look!

I'll have a look at using the lower level APIs. I have on a few occasions found the APIs that I was using a little too high level. In particular, I was wanting at one point to store slices of relocations, but because the APIs were all iterator-based, I ended up needing to do something else instead. But you're right, if it I just read the relocation section bytes, then call object::slice_from_bytes, I can just get the raw relocations directly.

I defined my own structs for ELF types mostly because I initially didn't realise that I could write via the types that the object crate provided. Once I did realise, I figured object's types were doing some things that I figured I didn't need - supporting writing to unaligned bytes and supporting big endian. But I suspect I won't pay any performance penalty for those features, so I should probably just switch over.

**Comment by davidlattimore** [comment]
I've switched several structs over to those provided by the `object` crate. One downside is that because there are some structs that `object` doesn't define, such as the format of the eh_frame header, I now need to work with two different `Pod` interfaces - `object`'s  and `bytemuck`'s. But it's not too bad.

**Comment by philipc** [comment]
> I'll have a look at using the lower level APIs.

I could work on this if you want. The lower level APIs haven't seen a lot of use, so there's probably some rough edges in `object` that need fixing.

> I now need to work with two different Pod interfaces - object's and bytemuck's

You could use `object`'s `Pod` for everything. Or we could switch `object` to use `bytemuck`. (The reason I haven't done that is because `bytemuck` expects you to have the exact size, but when reading it is common to have trailing bytes, so I would still have to repeat all the size calculations that `bytemuck` does. This is similar to why https://crates.io/crates/bytes-cast exists.)

**Comment by davidlattimore** [comment]
> I could work on this if you want. The lower level APIs haven't seen a lot of use, so there's probably some rough edges in `object` that need fixing.

By all means! Contributions are definitely welcome! If anything doesn't make sense, let me know, and I'll try to document it better. I'm also happy to do video calls if you want to discuss stuff - my calendar is linked from github.

I was thinking some more about the `bytemuck` vs `object` Pod approaches. Another big difference besides what you mentioned with trailing bytes is that `object::Pod` handles unaligned reads/writes when each field is read/written, whereas `bytemuck` doesn't, so if the value might be unaligned, you need to copy the whole struct. I know my output is always properly aligned, so for writing, bytemuck's approach is fine. However for reading, I need to be able to cope with things unaligned because archives only have 2-byte alignment - so there, `object`'s approach is definitely better - although plausibly better still would be to make the code generic over whether we're aligned, then switch at a higher level. I suspect it probably doesn't make any difference on x86 anyway, since AFAIK the same instructions are used for aligned and unaligned access. It might make more of a difference on ARM where different instructions are used, but that's a problem for another day.
